import time, random, json, sys
import paho.mqtt.client as mqtt
import socket

MQTT_BROKER = "10.0.0.254"  # Root namespace IP on Mininet switch
ROOM = sys.argv[1] if len(sys.argv) > 1 else "CR101"
SENSOR_ID = sys.argv[2] if len(sys.argv) > 2 else socket.gethostname()

client = mqtt.Client()

# Retry MQTT connect until success
while True:
    try:
        client.connect(MQTT_BROKER, 1883, 60)
        break
    except Exception as e:
        print(f"Connection failed, retrying in 5 seconds: {e}")
        time.sleep(5)

def simulate_environment():
    timestamp = time.strftime('%Y-%m-%dT%H:%M:%SZ')
    # Print timestamp generated by sensor
    print("SENSOR SIDE TIMESTAMP (about to publish):", timestamp)
    return {
        'sensor_id': SENSOR_ID,
        'room': ROOM,
        'temperature': round(random.uniform(18, 35), 1),
        'humidity': round(random.uniform(25, 75), 1),
        'light': round(random.uniform(100, 1200), 1),
        'co2': round(random.uniform(300, 1500), 1),
        'timestamp': timestamp
    }

print(f"Sensor {SENSOR_ID} starting in room {ROOM}...")

while True:
    data = simulate_environment()
    for metric in ['temperature', 'humidity', 'light', 'co2']:
        payload = json.dumps({
            'sensor_id': SENSOR_ID,
            'room': ROOM,
            'type': metric,
            'value': data[metric],
            'timestamp': data['timestamp']
        })
        client.publish(f'sensors/{metric}/{ROOM}/{SENSOR_ID}', payload)
    print(f"[{ROOM}] {data}")
    time.sleep(5)